= JWS validator Policy documentation.

== Phase

|===
|onRequest |onResponse

| X
|
|===


== Context

JWT in JWS format enables secure content to be shared across security domains.

JWS (Json Web Signature) standard RFC : https://tools.ietf.org/html/rfc7515

JOSE Header standard RFC : https://tools.ietf.org/html/rfc7515#section-4

JWT (Json Web Token) standard RFC : https://tools.ietf.org/html/rfc7519

== JWT/JWS Example

A JWT is composed of three part : header, payload, signature.
You can see some sample here : http://jwt.io

The header will contain attributes indicating the algorithm used to sign the token.

The payload contains some informations inserted by the AS (Authorization Server) such as expiration date, uid of the user, etc…

Both header & payload are encoded on Base64, so anyone can read the content.

The third and last part is the signature. (Please see RFC for more details)

== Policy aim

Policy aims to validate the token signature, certificate information & expiration date before sending the api call to the target backend.

== Input

----
======================= =================================================
Request Method          POST
Request Content-Type    application/jose+json
Request Body            eyJ0....ifQ.eyJzdWIiOiI...lIiwiYWRtaW4iOnRydWV9.TJVA95...h7HgQ
Response Codes          Backend Response or 401 Unauthorized
======================= =================================================
----

According to JWS rfc : https://tools.ietf.org/html/rfc7515#section-4.1.10, the JWT/JWS header must contains the following information in order to provide correct content type to the backend :

The "typ" value "JOSE" can be used by applications to indicate that this object is a JWS or JWE using the JWS Compact Serialization or the JWE Compact Serialization.
The "typ" value "JOSE+JSON" can be used by applications to indicate that this object is a JWS or JWE  using the JWS JSON Serialization or the JWE JSON Serialization.

The "cty" (content type) Header Parameter is used by JWS applications to declare the media type [IANA.MediaTypes] of the secured content (the payload).
To keep messages compact in common situations, it is RECOMMENDED that senders omit an "application/" prefix of a media type value in a "cty" Header Parameter when no other '/' appears in the media type value.

A recipient using the media type value MUST treat it as if "application/" were prepended to any "cty" value not containing a '/'.

Here, it's a valid example of JWS Header :

[source, json]
----
{
 "typ":"JOSE+JSON",
 "cty":"json",
 "alg":"RS256",
 "x5c":"string",
 "kid":"string"
}
----

== Configuration

|===
|Property |Required |Description |Type |Default

|checkCertificateValidity||Check if the certificate used to sign the JWT is valid with correct 'not_before' and 'not_after' dates|boolean|false.
|checkCertificateRevocation||Check if the certificate used to sign the JWT is not revoked via the CRL Distribution Points. The CRL is stored inside the X509v3 CRL Distribution Extension Points.|boolean|false
|===

To validate the token signature, the policy need to use the associated public key set into into gravitee gateway settings, _gravitee.yml_ file.

[source, yml]
----
policy:                  
  jws:
    kid:
      default: ssh-rsa myValidationKey anEmail@domain.com
      kid-2016: /filepath/to/pemFile/certificate.pem
----

On this mode, the policy will inspect the jwt/jws :

** header in order to extract the key id (kid attribute) of the public key. If none then we set it as ‘default’.

The gateway will be able to retrieve the corresponding public key and the JOSE Header with "x5c" (X.509 Certificate Chain) Header Parameter will be used to verify certificate information
and check that this JWT was signed using the private key that corresponds to the specified public key.

== Http Status Code

|===
|Code |Message

| ```401```
| In case of bad token format, content, signature, certificate, expired token or any others problem which forbid the policy to validate the token

|===

